// create an array containing list of sounds:
export const sounds = {
    folder: "sounds",
    soundsFiles: [
        { file: "ah-haha.mp3", key: "q" },
        { file: "among-us-reveal.mp3", key: "w" },
        { file: "and-you-fail.mp3", key: "e" },
        { file: "anime-wow.mp3", key: "a" },
        { file: "ask-if-you-are-fine.mp3", key: "s" },
        { file: "be-right-back.mp3", key: "d" },
        { file: "beatboxing.mp3", key: "f" },
        { file: "bite-of-87.mp3", key: "b" },
        { file: "boss-music.mp3", key: "j" },
        { file: "bruh.mp3", key: "k" },
        { file: "cant-touch-this.mp3", key: "l" },
        { file: "cat-vibing.mp3", key: "z" },
        { file: "confusing.mp3", key: "x" },
        { file: "deja-vu.mp3", key: "c" },
        { file: "didnt-laugh.mp3", key: "v" },
        { file: "disgusting.mp3", key: "b" },
        { file: "do-you-know-the-way.mp3", key: "n" },
        { file: "dr-livesey.mp3", key: "m" },
        { file: "dun-dun-dun.mp3", key: "," },
        { file: "ehhhh-eh-eh-eh.mp3", key: "." },
        { file: "emotional-damage.mp3", key: "/" },
        { file: "epic-sax.mp3", key: "1" },
        { file: "excuse-me-pewds.mp3", key: "2" },
        { file: "fail.mp3", key: "3" },
        { file: "fbi-open-up.mp3", key: "4" },
        { file: "got-you.mp3", key: "5" },
        { file: "helicopter.mp3", key: "6" },
        { file: "here-we-go-again.mp3", key: "7" },
        { file: "hes-dont-it.mp3", key: "8" },
        { file: "huh.mp3", key: "9" },
        { file: "illuminati.mp3", key: "0" },
        { file: "it-is-what-it-is.mp3", key: "!" },
        { file: "john-cena.mp3", key: "&" },
        { file: "jojo-serious.mp3", key: "*" },
        { file: "legally-blind.mp3", key: "(" },
        { file: "made-by.mp3", key: ")" },
        { file: "minecraft-drink.mp3", key: "-" },
        { file: "mission-failed.mp3", key: "_" },
        { file: "nani.mp3", key: "r" },
        { file: "nyan-cat.mp3", key: "t" },
        { file: "obiwan-hello.mp3", key: "y" },
        { file: "oh-my-god.mp3", key: "u" },
        { file: "oh-my-god-trolls.mp3", key: "i" },
        { file: "oh-no.mp3", key: "o" },
        { file: "oh-no-laugh.mp3", key: "p" },
        { file: "okay.mp3", key: "enter" },
        { file: "omg-wow.mp3", key: "g" },
        { file: "ora-ora-ora.mp3", key: "h" },
        { file: "outro.mp3", key: "ø" },
        { file: "dont-give-a-shit.mp3", key: "æ" },
        { file: "power-of-god-and-anime.mp3", key: "#" },
        { file: "quack.mp3", key: '"' },
        { file: "run.mp3", key: "¤" },
        { file: "sad.mp3", key: "§" },
        { file: "shesh.mp3", key: "|" },
        { file: "shooting-stars.mp3", key: "%" },
        { file: "shrek-mad.mp3", key: "=" },
        { file: "slumber.mp3", key: "+" },
        { file: "smash-bros-join.mp3", key: "{" },
        { file: "spiderman.mp3", key: "}" },
        { file: "still-garbage.mp3", key: "[" },
        { file: "suprise-madafaka.mp3", key: "]" },
        { file: "trollolo.mp3", key: "'" },
        { file: "wake-me-up.mp3", key: ";" },
        { file: "we-got-him.mp3", key: ":" },
        { file: "weeeeee.mp3", key: "<" },
        { file: "what-the-dog-doing.mp3", key: ">" },
        { file: "why.mp3", key: "?" },
        { file: "why-so-spicy.mp3", key: "£" },
    ],
    drumComponents: [], // to store references to drum components
};